CREATE TABLE t_api_keys (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    API_KEY VARCHAR(255) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    TERMINATED_DATE DATE DEFAULT NULL,
    MODIFIED_DATETIME DATETIME DEFAULT NOW()
);